# Generated by Django 5.0.4 on 2024-05-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
