# Generated by Django 5.0.4 on 2024-05-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_path_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='user',
            new_name='user_id',
        ),
    ]
